//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tbl_dashbord
    {
        public int ID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string IssureName { get; set; }
        public Nullable<DateTime> DateOfIssue { get; set; }
        public Nullable<DateTime> DateOfReturn { get; set; }
        public Nullable<int> Fine { get; set; }
        public DateTime Date { get; internal set; }

    }
}
